### Creation of Matrix

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
m = np.array([[3,4],[2,9],[7,2]])
m

array([[3, 4],
       [2, 9],
       [7, 2]])

In [3]:
m.shape

(3, 2)

In [4]:
"""class Person:
    def __init__(self,n,a):
        self.name = n
        self.age = a
    def show(self):
        print('Values are:', self.name,self.age)"""

"class Person:\n    def __init__(self,n,a):\n        self.name = n\n        self.age = a\n    def show(self):\n        print('Values are:', self.name,self.age)"

In [5]:
m.min()

2

In [6]:
type(m)

numpy.ndarray

In [7]:
m.size

6

In [8]:
m.mean()

4.5

In [9]:
m.max()

9

In [10]:
v = np.array([3,7,8,5,9,1,6,3])
v

array([3, 7, 8, 5, 9, 1, 6, 3])

In [11]:
v.size

8

In [12]:
v.reshape(2,4)

array([[3, 7, 8, 5],
       [9, 1, 6, 3]])

In [13]:
v.dtype

dtype('int32')

In [14]:
m = np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]], dtype=np.int8)

In [15]:
m

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [16]:
m.flatten()

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

In [17]:
m.reshape(-1,3)

array([[3, 4, 8],
       [0, 2, 8],
       [1, 3, 1],
       [9, 5, 6]], dtype=int8)

In [18]:
m.reshape(-1,4)

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [19]:
m.reshape(-1)

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

### Matrix Operations

In [20]:
m

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [21]:
m[1][2]

1

In [22]:
for row in m:
    print(row)

[3 4 8 0]
[2 8 1 3]
[1 9 5 6]


In [23]:
for i in range(0,3):
    for j in range(0,4):
        print(f"{m[i][j]}", end=" ")
    print()

3 4 8 0 
2 8 1 3 
1 9 5 6 


In [24]:
for row in m:
    for value in row:
        print(value, end=" ")
    print()

3 4 8 0 
2 8 1 3 
1 9 5 6 


In [25]:
for row in m:
    print(*row)

3 4 8 0
2 8 1 3
1 9 5 6


### Addition 

In [26]:
m1 = np.array([[8,5,6],[2,1,6],[0,2,8]])
m2 = np.array([[5,8,3],[5,4,7],[1,8,3]])

In [27]:
m3 = m1 + m2
m3

array([[13, 13,  9],
       [ 7,  5, 13],
       [ 1, 10, 11]])

In [28]:
m3 = m1 * m2
m3

array([[40, 40, 18],
       [10,  4, 42],
       [ 0, 16, 24]])

In [29]:
m1.dot(m2)

array([[ 71, 132,  77],
       [ 21,  68,  31],
       [ 18,  72,  38]])

### Subtraction

In [30]:
m3 = m2 - m1
m3

array([[-3,  3, -3],
       [ 3,  3,  1],
       [ 1,  6, -5]])

### Scalar Multiplication

In [31]:
m1, m1 * 2

(array([[8, 5, 6],
        [2, 1, 6],
        [0, 2, 8]]),
 array([[16, 10, 12],
        [ 4,  2, 12],
        [ 0,  4, 16]]))

In [32]:
m3 = 2 * (m1 + m2)

In [33]:
m4 = 2 * m1 + 2 * m2

In [34]:
m3, m4

(array([[26, 26, 18],
        [14, 10, 26],
        [ 2, 20, 22]]),
 array([[26, 26, 18],
        [14, 10, 26],
        [ 2, 20, 22]]))

In [35]:
m5 = (4 + 5)*m1

In [36]:
m6 = 4*m1 + 5*m1

In [37]:
m5, m6

(array([[72, 45, 54],
        [18,  9, 54],
        [ 0, 18, 72]]),
 array([[72, 45, 54],
        [18,  9, 54],
        [ 0, 18, 72]]))

In [38]:
-1 * m5

array([[-72, -45, -54],
       [-18,  -9, -54],
       [  0, -18, -72]])

### Matrix Multiplication

In [39]:
m1, m2

(array([[8, 5, 6],
        [2, 1, 6],
        [0, 2, 8]]),
 array([[5, 8, 3],
        [5, 4, 7],
        [1, 8, 3]]))

In [40]:
#NOTE:
#@ Symbol for matrix multiplication
#matmul() function for matrix multiplication

m1 @ m2

array([[ 71, 132,  77],
       [ 21,  68,  31],
       [ 18,  72,  38]])

In [41]:
(m1 @ m2), (m2 @ m1)

(array([[ 71, 132,  77],
        [ 21,  68,  31],
        [ 18,  72,  38]]),
 array([[ 56,  39, 102],
        [ 48,  43, 110],
        [ 24,  19,  78]]))

In [42]:
np.matmul(m1,m2)

array([[ 71, 132,  77],
       [ 21,  68,  31],
       [ 18,  72,  38]])

### Matrix Transpose

In [43]:
#NOTE:-
#T is used for transpose the matrix also we can use np.transpose().

m1.T

array([[8, 2, 0],
       [5, 1, 2],
       [6, 6, 8]])

In [44]:
m1

array([[8, 5, 6],
       [2, 1, 6],
       [0, 2, 8]])

In [45]:
np.transpose(m1)

array([[8, 2, 0],
       [5, 1, 2],
       [6, 6, 8]])

In [46]:
x = int(input("Enter number of rows:"))
y = int(input("Enter number of columns:"))
a = np.zeros((x,y))
for i in range(x):
    for j in range(y):
        b = input("Enter Values:")
        a[i][j] = b
a

Enter number of rows:2
Enter number of columns:2
Enter Values:2
Enter Values:3
Enter Values:4
Enter Values:5


array([[2., 3.],
       [4., 5.]])

In [47]:
a.T

array([[2., 4.],
       [3., 5.]])

In [48]:
x = int(input("Enter number of rows:"))
y = int(input("Enter number of columns:"))
mat = np.zeros(x * y)
for i in range(len(mat)):
    mat[i] = int(input("Enter Values:"))
    
mat = mat.reshape(x,y)
print("Matrix:\n", mat)
print("Transpose:\n",mat.T)

Enter number of rows:2
Enter number of columns:2
Enter Values:3
Enter Values:4
Enter Values:5
Enter Values:6
Matrix:
 [[3. 4.]
 [5. 6.]]
Transpose:
 [[3. 5.]
 [4. 6.]]


In [49]:
(m1 @ m2).T,  m2.T @ m1.T

(array([[ 71,  21,  18],
        [132,  68,  72],
        [ 77,  31,  38]]),
 array([[ 71,  21,  18],
        [132,  68,  72],
        [ 77,  31,  38]]))

In [50]:
m1.T + m2.T, (m1 + m2).T

(array([[13,  7,  1],
        [13,  5, 10],
        [ 9, 13, 11]]),
 array([[13,  7,  1],
        [13,  5, 10],
        [ 9, 13, 11]]))

### Trace of Matrix 

In [51]:
m1

array([[8, 5, 6],
       [2, 1, 6],
       [0, 2, 8]])

In [52]:
m1[0][0] + m1[1][1] + m1[2][2]

17

In [53]:
m1[2] = 12

In [54]:
m1

array([[ 8,  5,  6],
       [ 2,  1,  6],
       [12, 12, 12]])

In [55]:
m1[2][1] = 9

In [56]:
m1[2][2] = 11

In [57]:
m1

array([[ 8,  5,  6],
       [ 2,  1,  6],
       [12,  9, 11]])

In [58]:
add = 0
rn = 0
for row in m1:
    add = add + row[rn]
    rn += 1

In [59]:
add

20

In [60]:
rn

3

In [61]:
np.trace(m1)

20

In [62]:
m1 @ m2

array([[ 71, 132,  77],
       [ 21,  68,  31],
       [116, 220, 132]])

In [63]:
m2 @ m1

array([[ 92,  60, 111],
       [132,  92, 131],
       [ 60,  40,  87]])

In [64]:
np.trace(m1 @ m2), np.trace(m2 @ m1)

(271, 271)

In [65]:
np.trace(m1), np.trace(m1.T)

(20, 20)

In [66]:
2 * np.trace(m1), np.trace(2 * m1)

(40, 40)

### Determinant of Matrix

In [67]:
m1

array([[ 8,  5,  6],
       [ 2,  1,  6],
       [12,  9, 11]])

In [68]:
np.linalg.det(m1)

-57.999999999999986

In [69]:
8 * (11-54) - 5 * (22-72) + 6 * (18-12)

-58

In [70]:
np.linalg.det(m2)

-176.00000000000009

### Inverse of the matrix

In [71]:
np.linalg.inv(m1)

array([[ 0.74137931,  0.01724138, -0.4137931 ],
       [-0.86206897, -0.27586207,  0.62068966],
       [-0.10344828,  0.20689655,  0.03448276]])

### Rank of the Matrix

In [72]:
a1 = np.array([[1,2],[2,4]])
a1

array([[1, 2],
       [2, 4]])

In [73]:
np.linalg.matrix_rank(a1)

1

In [74]:
a2 = np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [75]:
np.linalg.matrix_rank(a2)

2

In [80]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.matrix_rank(a3)

2

In [81]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Row Matrix

In [83]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
R = a3.reshape(1,-1)
R

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [87]:
R.shape

(1, 9)

### Column Matrix

In [89]:
C = R.T
C

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
C1 = R.reshape(-1,1)
C1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [91]:
C.shape

(9, 1)

### Square Matrix

In [98]:
def isSquareMatrix(a3):
    if a3.shape[0] == a3.shape[1]:
        return True
    else:
        return False

In [100]:
isSquareMatrix(a3)

True

In [106]:
s=np.zeros([4,4], dtype=np.int8)
s = s+4

In [107]:
s

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

### Rectangular Matrix

In [110]:
def isRectangularMatrix(a3):
    if a3.shape[0] != a3.shape[1]:
        return True
    else:
        return False

In [111]:
isRectangularMatrix(a3)

False

In [112]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
isRectangularMatrix(C)

True

In [114]:
isRectangularMatrix(m1)

False

In [120]:
b=np.zeros([4,4], dtype=np.int8)
for i in range(4):
    b[i][i] = 4
    
b

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int8)

In [145]:
def isDiagonalMatrix(a3):
    for i in range(a3.shape[0]):
        for j in range(a3.shape[1]):
            if i != j and a3[i][j] != 0:
                return False
    return True

In [146]:
isDiagonalMatrix(a3)

False

In [147]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Identity Matrix

In [148]:
I = np.zeros([4,4], dtype=np.int8)
for i in range(4):
    I[i][i] = 1
    
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [149]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

### Symmetric Matrix

In [155]:
S1 = np.array([[2,3,6],[3,4,5],[6,5,9]])
S1

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [171]:
(S1 == S1.T).sum()

9

In [173]:
S1.size

9

In [174]:
((S1 == S1.T).sum()) == S1.size

True

In [177]:
def isSymmetric(S1):
    if (S1 == S1.T).sum() == S1.size:
        return True
    return False

In [178]:
isSymmetric(S1)

True

### Skew-Symmetric Matrix

In [179]:
S2 = np.array([[0,3],[-3,0]])
S2

array([[ 0,  3],
       [-3,  0]])

In [180]:
-S2

array([[ 0, -3],
       [ 3,  0]])

In [181]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

In [188]:
def isSkewSymmetric(S2):
    if (-S2 == S2.T).sum() == S2.size:
        return True
    return False

In [191]:
isSkewSymmetric(S2)

True

### Eigen Vectors

In [193]:
A = np.array([[-6,3],[4,5]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-7.  6.]
Eigenvectors:
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [201]:
A @ eigenvectors

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [202]:
eigenvalues * eigenvectors

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])